---
name: dockerlint

description: "Docker Lint via Hadolint"

inputs:
  image_dockerfile:
    required: true
    type: string
  upload:
    required: false
    type: boolean
    default: false

outputs: {}

runs:
  using: composite
  steps:
    - name: DOCKER_LINT
      uses: hadolint/hadolint-action@v3.1.0
      with:
         dockerfile: ${{ inputs.image_dockerfile }}
         format: sarif
         output-file: hadolint-results.sarif
         no-fail: true

    - name: DOCKER_LINT_UPLOAD_RESULTS
      uses: github/codeql-action/upload-sarif@v2
      if: inputs.upload
      continue-on-error: true
      with:
        sarif_file: hadolint-results.sarif
