---
name: dockerrelease

inputs:
  image_ref:
    required: true
    type: string

outputs: {}

runs:
  using: composite
  steps:
    - name: DOCKER_SETUP
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

    - name: DOCKER_PUSH
      shell: bash
      run: |
        docker push ${{ inputs.image_ref }}
