---
name: dockerrelease

inputs:
  image_ref:
    required: true
    type: string

outputs: {}

runs:
  using: composite
  steps:
    - name: DOCKER_SETUP
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

    - name: DOCKER_REGISTRY_LOGIN
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: DOCKER_PUSH
      shell: bash
      run: |
        docker push ${{ inputs.image_ref }}
