---
name: dockertest

on:
  workflow_call:
    inputs:
      git_revision:
        required: false
        type: string
        default: HEAD
      image_ref:
        required: true
        type: string
      cst_config:
        required: true
        type: string
      cst_format:
        required: false
        type: string
        default: text
    secrets:
      token:
        required: false
runs:
  using: composite
  steps:
    - name: GIT_CHECKOUT
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: "${{ inputs.git_revision }}"

    - name: DOCKER_SETUP
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

    - name: DOCKER_TEST_INSTALL
      run: |
        curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
        chmod +x container-structure-test-linux-amd64
        mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

    - name: DOCKER_TEST_RUN
      run: |
        container-structure-test test --image ${{ inputs.image_ref }} --config ${{ inputs.cst_config }} --format ${{ inputs.cst_format }}
