---
name: dockerbuild

inputs:
  image_dockerfile:
    required: true
    type: string
  image_context:
    required: true
    type: string
  image_name:
    required: true
    type: string

outputs:
  image_name:
    description: "Image name"
    value: "${{ steps.DOCKER_BUILD.image_name }}"
  image_version:
    description: "Image version"
    value: "${{ steps.DOCKER_BUILD.image_version }}"
  image_uri:
    description: "Image URI (name:tag)"
    value: "${{ steps.DOCKER_BUILD.image_uri }}"

runs:
  using: composite
  steps:
    - name: DOCKER_QEMU_SETUP
      uses: docker/setup-qemu-action@v3

    - name: DOCKER_BUILDX_SETUP
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

    - name: DOCKER_BUILD_VERSIONING
      id: DOCKER_BUILD
      shell: bash
      run: |
        IMAGE_NAME="${{ inputs.image_name }}"
        IMAGE_DOCKERFILE="${{ inputs.image_dockerfile }}"
        IMAGE_VERSION="v$(date +%Y%m%d)-$IMAGE_REVISION"
        IMAGE_VERSION_FILE="$(dirname $IMAGE_DOCKERFILE)/IMAGE_VERSION"
        
        if [ -f "$IMAGE_VERSION_FILE" ]; then
          IMAGE_VERSION="$(cat $IMAGE_VERSION_FILE)"
        fi
        
        echo "image_version=$IMAGE_VERSION" >> $GITHUB_OUTPUT
        echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
        echo "image_uri=$IMAGE_NAME:$IMAGE_VERSION" >> $GITHUB_OUTPUT
        
        echo "GITHUB OUTPUT:"
        echo "$(cat $GITHUB_OUTPUT)"
        
        # IMPORTANT:
        # when referencing local actions $GITHUB_OUTPUT is not working.
        # remote users can use outputs as usual.
        #
        # see https://github.com/actions/runner/issues/2009
        
        echo "image_version=$IMAGE_VERSION" >> $GITHUB_ENV
        echo "image_name=$IMAGE_NAME" >> $GITHUB_ENV
        echo "image_uri=$IMAGE_NAME:$IMAGE_VERSION" >> $GITHUB_ENV

    - name: DOCKER_BUILD
      uses: docker/build-push-action@v5
      with:
        context: "${{ inputs.image_context }}"
        file: "${{ inputs.image_dockerfile }}"
        push: false
        tags: |
          ${{ inputs.image_name }}:latest
          ${{ inputs.image_name }}:${{ env.image_version }}
        platforms: |
          linux/arm64
          linux/amd64
        build-args: |
          IMAGE_VERSION=${{ github.sha }}
          IMAGE_REVISION=${{ github.sha }}
        labels: |
          org.opencontainers.image.authors="ShopEntrance <shozu@otto.de>"
          org.opencontainers.image.vendor="ShopEntrance <shozu@otto.de>"
          org.opencontainers.image.version="${{ github.sha }}"
          org.opencontainers.image.revision="${{ github.sha }}"
          org.opencontainers.image.source="https://github.com/${{ github.repository }}"
        annotations: |
          org.opencontainers.image.authors="ShopEntrance <shozu@otto.de>"
          org.opencontainers.image.vendor="ShopEntrance <shozu@otto.de>"
          org.opencontainers.image.version="${{ github.sha }}"
          org.opencontainers.image.revision="${{ github.sha }}"
          org.opencontainers.image.source="https://github.com/${{ github.repository }}"

