---
name: dockersign

inputs:
  image_ref:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: CRANE_INSTALL
      uses: imjasonh/setup-crane@v0.3

    - name: COSIGN_INSTALL
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v2.0.2'

    - name: COSIGN_SIGN
      env:
        COSIGN_EXPERIMENTAL: "1"
      run: |
        IMAGE_DIGEST=$(crane digest ${{ inputs.image_ref }})
        IMAGE_REF="${{ inputs.image_ref }}"
        
        cosign sign --yes=true --tlog-upload=false $IMAGE_REF@$IMAGE_DIGEST
