---
name: dockerscan

inputs:
  git_revision:
    required: false
    type: string
    default: HEAD
  image_ref:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: DOCKER_SCAN_WITH_TRIVY
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ inputs.image_ref }}'
        format: 'sarif'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        output: 'trivy-results.sarif'
        trivyignores: ".trivyignore"

    - name: DOCKER_SCAN_WITH_TRIVY_UPLOAD_RESULTS
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

