---
on:
  workflow_dispatch:
    inputs: {}

permissions:
  packages: write
  id-token: write
  security-events: write
  statuses: write
  contents: read
  checks: read

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: GIT_CHECKOUT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "DOCKER_LINT"
        id: "DOCKER_LINT_ROOT"
        uses: ./actions/dockerlint
        with:
          image_dockerfile: "sample/Dockerfile"

      - name: "DOCKER_BUILD"
        id: "DOCKER_BUILD_ROOT"
        uses: ./actions/dockerbuild
        with:
          image_dockerfile: "sample/Dockerfile"
          image_context: "sample"
          image_name: "ghcr.io/${{ github.repository }}/sample"

      - name: "DOCKER_TEST"
        id: "DOCKER_TEST_ROOT"
        uses: ./actions/dockertest
        with:
          image_ref: "${{ env.image_uri }}"
          cst_config: "sample/containertest.yaml"

      - name: "DOCKER_SCAN"
        id: "DOCKER_SCAN_ROOT"
        uses: ./actions/dockerscan
        with:
          image_ref: "${{ env.image_uri }}"

      - name: "DOCKER_RELEASE"
        id: "DOCKER_RELEASE_ROOT"
        uses: ./actions/dockerrelease
        with:
          image_ref: "${{ env.image_uri }}"
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: "DOCKER_SIGN"
        id: "DOCKER_SIGN_ROOT"
        uses: ./actions/dockersign
        with:
          image_ref: "${{ env.image_uri }}"
