---
on:
  workflow_dispatch:
    inputs: {}

permissions:
  packages: write
  id-token: write
  security-events: write
  statuses: write
  contents: read
  checks: read

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: GIT_CHECKOUT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "${{ github.sha }}"

      - name: "DOCKER_LINT"
        id: "DOCKER_LINT"
        uses: ./dockerlint/action.yml
        with:
          image_dockerfile: "sample/Dockerfile"

      - name: "DOCKER_BUILD"
        id: "DOCKER_BUILD"
        uses: ./dockerbuild/action.yml
        with:
          image_dockerfile: "sample/Dockerfile"
          image_context: "sample"
          image_name: "ghcr.io/${{ github.event.repository.name }}/sample"

      - name: "DOCKER_TEST"
        id: "DOCKER_TEST"
        uses: ./dockertest/action.yml
        with:
          image_ref: "${{ steps.DOCKER_BUILD.IMAGE_URI }}"
          cst_config: "sample/containertest.yaml"

      - name: "DOCKER_SCAN"
        id: "DOCKER_SCAN"
        uses: ./dockerscan/action.yml
        with:
          image_ref: "${{ steps.DOCKER_BUILD.IMAGE_URI }}"

      - name: "DOCKER_RELEASE"
        id: "DOCKER_RELEASE"
        uses: ./dockerrelease/action.yml
        with:
          image_ref: "${{ steps.DOCKER_BUILD.IMAGE_URI }}"

      - name: "DOCKER_SIGN"
        id: "DOCKER_SIGN"
        uses: ./dockersign/action.yml
        with:
          image_ref: "${{ steps.DOCKER_BUILD.IMAGE_URI }}"
