---
on:
  workflow_dispatch:
    inputs: {}

permissions:
  packages: write
  id-token: write
  security-events: write
  statuses: write
  contents: read
  checks: read

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: GIT_CHECKOUT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "DOCKER_LINT"
        id: "DOCKER_LINT"
        uses: ./actions/dockerlint
        with:
          image_dockerfile: "sample/Dockerfile"

      - name: "DOCKER_BUILD"
        id: "DOCKER_BUILD"
        uses: ./actions/dockerbuild
        with:
          image_dockerfile: "sample/Dockerfile"
          image_context: "sample"
          image_name: "ghcr.io/${{ github.event.repository.name }}/sample"

      - name: DEBUG
        run: |
          echo "IMAGE_URI=${{ steps.DOCKER_BUILD.outputs.IMAGE_URI }}"
          echo "IMAGE_URI=${{ toJSON(steps.DOCKER_BUILD.outputs) }}"

      - name: "DOCKER_TEST"
        id: "DOCKER_TEST"
        uses: ./actions/dockertest
        with:
          image_ref: "${{ steps.DOCKER_BUILD.outputs.IMAGE_URI }}"
          cst_config: "sample/containertest.yaml"

      - name: "DOCKER_SCAN"
        id: "DOCKER_SCAN"
        uses: ./actions/dockerscan
        with:
          image_ref: "${{ steps.DOCKER_BUILD.outputs.IMAGE_URI }}"

      - name: "DOCKER_RELEASE"
        id: "DOCKER_RELEASE"
        uses: ./actions/dockerrelease
        with:
          image_ref: "${{ steps.DOCKER_BUILD.outputs.IMAGE_URI }}"

      - name: "DOCKER_SIGN"
        id: "DOCKER_SIGN"
        uses: ./actions/dockersign
        with:
          image_ref: "${{ steps.DOCKER_BUILD.outputs.IMAGE_URI }}"
